language: node_js
node_js:
  - "8"
cache: npm

jobs:
  include:
    - stage: test/lint
      script: 
        - npm run test
        - npm run lint
    - stage: build
      script: npm run build
      script: npx semantic-release